import{n as e}from"./assets/rolldown-runtime-DNdEV4Dn.js";import{n as t,t as n}from"./assets/vendor-BFO8Ugs7.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin===`use-credentials`?t.credentials=`include`:e.crossOrigin===`anonymous`?t.credentials=`omit`:t.credentials=`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var r=e(t(),1),i=e(n(),1),a=document.querySelector(`.gallery`),o=document.querySelector(`.loader`),s;function c(){a.innerHTML=``}function l(){o.classList.add(`active`)}function u(){o.classList.remove(`active`)}function d(e){l(),requestAnimationFrame(()=>{a.innerHTML=e.map(({webformatURL:e,largeImageURL:t,tags:n,likes:r,views:i,comments:a,downloads:o})=>`
        <li class="gallery-item">
          <a href="${t}">
            <img src="${e}" alt="${n}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><span class="label">Likes:</span> <span class="value">${r}</span></p>
            <p class="info-item"><span class="label">Views:</span> <span class="value">${i}</span></p>
            <p class="info-item"><span class="label">Comments:</span> <span class="value">${a}</span></p>
            <p class="info-item"><span class="label">Downloads:</span> <span class="value">${o}</span></p>
          </div>
        </li>
      `).join(``);let t=a.querySelectorAll(`img`),n=0;function r(){n++,n===t.length&&u()}t.length===0?u():t.forEach(e=>{e.complete?r():(e.addEventListener(`load`,r),e.addEventListener(`error`,r))}),s?s.refresh():s=new i.default(`.gallery a`,{captionsData:`alt`,captionDelay:250,showCounter:!0,nav:!0,close:!0,overlay:!0})})}var f=document.querySelector(`.form`),p=`55082106-4cb46bb19233a000c0dff9eca`;function m(e){let t=`https://pixabay.com/api/?key=${p}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&per_page=12`;return fetch(t).then(e=>{if(!e.ok)throw Error(`Network response was not ok`);return e.json()})}f.addEventListener(`submit`,function(e){e.preventDefault();let t=e.target.elements[`search-text`].value.trim();if(t===``){r.default.error({message:`Please enter a search query!`});return}c(),l(),m(t).then(e=>{if(!e.hits||e.hits.length===0){r.default.error({message:`Sorry, there are no images matching your search query. Please try again!`});return}d(e.hits),r.default.success({message:`Found ${e.totalHits} images!`})}).catch(()=>{r.default.error({message:`Something went wrong!`})}).finally(()=>{u()})});
//# sourceMappingURL=index.js.map