import{r as e}from"./assets/rolldown-runtime-Cq0jCQ29.js";import{n as t,r as n,t as r}from"./assets/vendor-DGJAgXav.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin===`use-credentials`?t.credentials=`include`:e.crossOrigin===`anonymous`?t.credentials=`omit`:t.credentials=`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var i=e(n(),1),a=e(t(),1),o=document.querySelector(`.gallery`),s=document.querySelector(`.loader`),c;function l(){o.innerHTML=``}function u(){s.classList.add(`active`)}function d(){s.classList.remove(`active`)}function f(e){u(),requestAnimationFrame(()=>{o.innerHTML=e.map(({webformatURL:e,largeImageURL:t,tags:n,likes:r,views:i,comments:a,downloads:o})=>`
        <li class="gallery-item">
          <a href="${t}">
            <img src="${e}" alt="${n}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><span class="label">Likes:</span> <span class="value">${r}</span></p>
            <p class="info-item"><span class="label">Views:</span> <span class="value">${i}</span></p>
            <p class="info-item"><span class="label">Comments:</span> <span class="value">${a}</span></p>
            <p class="info-item"><span class="label">Downloads:</span> <span class="value">${o}</span></p>
          </div>
        </li>
      `).join(``);let t=o.querySelectorAll(`img`),n=0;function r(){n++,n===t.length&&d()}t.length===0?d():t.forEach(e=>{e.complete?r():(e.addEventListener(`load`,r),e.addEventListener(`error`,r))}),c?c.refresh():c=new a.default(`.gallery a`,{captionsData:`alt`,captionDelay:250,showCounter:!0,nav:!0,close:!0,overlay:!0})})}var p=`55082106-4cb46bb19233a000c0dff9eca`,m=`https://pixabay.com/api/`;function h(e){return r.get(m,{params:{key:p,q:e,image_type:`photo`,orientation:`horizontal`,safesearch:!0}}).then(e=>e.data)}document.querySelector(`.form`).addEventListener(`submit`,e=>{e.preventDefault();let t=e.target.elements[`search-text`].value.trim();if(!t){i.default.error({message:`Please enter a search query!`});return}l(),u(),h(t).then(e=>{if(!e.hits||e.hits.length===0){i.default.error({message:`No images found!`});return}f(e.hits),i.default.success({message:`Found ${e.totalHits} images!`})}).catch(()=>{i.default.error({message:`Something went wrong!`})}).finally(()=>{d()})});
//# sourceMappingURL=index.js.map