import{r as e}from"./assets/rolldown-runtime-Cq0jCQ29.js";import{n as t,r as n,t as r}from"./assets/vendor-coROzJpy.js";(function(){let e=document.createElement(`link`).relList;if(e&&e.supports&&e.supports(`modulepreload`))return;for(let e of document.querySelectorAll(`link[rel="modulepreload"]`))n(e);new MutationObserver(e=>{for(let t of e)if(t.type===`childList`)for(let e of t.addedNodes)e.tagName===`LINK`&&e.rel===`modulepreload`&&n(e)}).observe(document,{childList:!0,subtree:!0});function t(e){let t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin===`use-credentials`?t.credentials=`include`:e.crossOrigin===`anonymous`?t.credentials=`omit`:t.credentials=`same-origin`,t}function n(e){if(e.ep)return;e.ep=!0;let n=t(e);fetch(e.href,n)}})();var i=e(n(),1),a=`55082106-4cb46bb19233a000c0dff9eca`,o=`https://pixabay.com/api/`;function s(e){return t.get(o,{params:{key:a,q:e,image_type:`photo`,orientation:`horizontal`,safesearch:!0}}).then(e=>e.data)}var c=e(r(),1),l=document.querySelector(`.gallery`),u=document.querySelector(`.loader`),d;function f(){l.innerHTML=``}function p(){u.classList.add(`active`)}function m(){u.classList.remove(`active`)}function h(e){p(),requestAnimationFrame(()=>{l.innerHTML=e.map(({webformatURL:e,largeImageURL:t,tags:n,likes:r,views:i,comments:a,downloads:o})=>`
        <li class="gallery-item">
          <a href="${t}">
            <img src="${e}" alt="${n}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><span class="label">Likes:</span> <span class="value">${r}</span></p>
            <p class="info-item"><span class="label">Views:</span> <span class="value">${i}</span></p>
            <p class="info-item"><span class="label">Comments:</span> <span class="value">${a}</span></p>
            <p class="info-item"><span class="label">Downloads:</span> <span class="value">${o}</span></p>
          </div>
        </li>
      `).join(``);let t=l.querySelectorAll(`img`),n=0;function r(){n++,n===t.length&&m()}t.length===0?m():t.forEach(e=>{e.complete?r():(e.addEventListener(`load`,r),e.addEventListener(`error`,r))}),d?d.refresh():d=new c.default(`.gallery a`,{captionsData:`alt`,captionDelay:250,showCounter:!0,nav:!0,close:!0,overlay:!0})})}document.querySelector(`.form`).addEventListener(`submit`,e=>{e.preventDefault();let t=e.target.elements[`search-text`].value.trim();if(t===``){i.default.error({message:`Please enter a search query!`});return}f(),p(),s(t).then(e=>{if(!e.hits||e.hits.length===0){i.default.error({message:`Sorry, there are no images matching your search query. Please try again!`});return}h(e.hits),i.default.success({message:`Found ${e.totalHits} images!`})}).catch(()=>{i.default.error({message:`Something went wrong!`})}).finally(()=>{m()})});
//# sourceMappingURL=index.js.map